---
- name: Ensure unzip is installed.
  package: 
    name: unzip 
    state: present

- name: Download and unarchive Packer.
  unarchive:
    src: "{{ packer_repo_url }}"
    dest: "{{ packer_bin_path }}"
    remote_src: true
    creates: "{{ packer_bin_path }}/packer"
    mode: 0755